# -*- coding: utf-8 -*-
"""
Type stubs for query.base module
"""

from abc import ABCMeta
from collections.abc import Generator
from functools import cache, cached_property
from typing import Callable, Optional, Self

from fudgeo import FeatureClass, Table
from pyproj import CRS, Transformer
from shapely import Polygon
from shapely.geometry.base import BaseMultipartGeometry

from spyops.environment import Extent
from spyops.environment.core import HasZM, ZMConfig
from spyops.geometry.config import GeometryConfig
from spyops.shared.enumeration import AttributeOption
from spyops.shared.hint import ELEMENT, EXTENT, FIELDS, GRID_SIZE, NAMES, XY_TOL


class AbstractElementQuery(metaclass=ABCMeta):

    _element: ELEMENT

    def __init__(self, element: ELEMENT) -> None: ...
    @staticmethod
    def _make_select(element: ELEMENT, field_names: str, where_clause: str) -> str: ...
    @staticmethod
    def _make_insert(element_name: str, field_names: str, field_count: int) -> str: ...
    def _field_names_and_count(self, element: ELEMENT) -> tuple[int, str, str]: ...
    @staticmethod
    def _concatenate(left: str, right: str) -> str: ...
    @property
    def source(self) -> ELEMENT: ...
    @property
    def select(self) -> str: ...
    @property
    def insert(self) -> str: ...


class AbstractFeatureClassQuery(AbstractElementQuery, metaclass=ABCMeta):

    _xy_tolerance: XY_TOL

    def __init__(self, element: FeatureClass, *, xy_tolerance: XY_TOL) -> None: ...
    def _get_transformer(self, feature_class: FeatureClass) -> Optional[Transformer]: ...
    @staticmethod
    def _get_transformer_or_guess(from_crs: CRS, to_crs: CRS) -> Optional[Transformer]: ...
    def _get_extent_polygon(self, extent: Extent, crs: CRS) -> Polygon: ...
    def _spatial_index_where(self, element: FeatureClass, extent: EXTENT) -> str: ...
    @cached_property
    def source_crs(self) -> CRS: ...
    @cached_property
    def source_transformer(self) -> Callable | None: ...
    @cached_property
    def spatial_reference_system(self): ...
    @cached_property
    def grid_size(self) -> GRID_SIZE: ...
    @property
    def source(self) -> FeatureClass: ...


class GroupQueryMixin:
    def _spatial_index_where(self, element: ELEMENT, extent: EXTENT) -> str: ...
    def _build_spatial_rank(self, element: ELEMENT) -> str: ...


class AbstractElementGroupQuery(GroupQueryMixin, AbstractElementQuery, metaclass=ABCMeta):
    def __init__(self, element: ELEMENT, fields: FIELDS) -> None: ...


class AbstractFeatureClassGroupQuery(GroupQueryMixin, AbstractFeatureClassQuery, metaclass=ABCMeta):
    def __init__(self, element: FeatureClass, fields: FIELDS, *, xy_tolerance: XY_TOL) -> None: ...


class AbstractSourceQuery(AbstractFeatureClassQuery, metaclass=ABCMeta):

    _target: FeatureClass

    def __init__(self, source: FeatureClass, target: FeatureClass, *, xy_tolerance: XY_TOL) -> None: ...
    def _get_unique_fields(self) -> FIELDS: ...
    def _get_target_shape_type(self) -> str: ...
    def _create_feature_class(self, shape_type: str, has_zm: HasZM) -> FeatureClass: ...
    @property
    def _has_zm(self) -> HasZM: ...
    def _make_full_query(self, element: FeatureClass) -> str: ...
    def _shared_extent(self, element: FeatureClass) -> EXTENT: ...
    def _make_disjoint_select(self, element: FeatureClass) -> str: ...
    def _get_extent_where(self, element: FeatureClass) -> str: ...
    def _make_intersection_query(self, element: FeatureClass, field_names: str, where_clause: str = ...) -> str: ...
    @cached_property
    def has_intersection(self) -> bool: ...
    @cached_property
    def zm_config(self) -> ZMConfig: ...
    @cached_property
    def geometry_config(self) -> GeometryConfig: ...
    @property
    def select(self) -> str: ...
    @property
    def select_intersect(self) -> str: ...
    @property
    def select_with_fid(self) -> str: ...
    @property
    def select_source(self) -> str: ...
    @cached_property
    def source_extent(self) -> EXTENT: ...
    @property
    def target(self) -> FeatureClass: ...
    @cached_property
    def target_empty(self) -> FeatureClass: ...
    @cached_property
    def target_full(self) -> FeatureClass: ...


class AbstractSourceUpdateQuery(AbstractSourceQuery):
    def __init__(self, source: FeatureClass) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> bool: ...
    @property
    def _short_name(self) -> str: ...
    def _prepare_source(self) -> None: ...
    @property
    def _intermediate_fields(self) -> FIELDS: ...
    def _delete_intermediate(self) -> None: ...
    @cached_property
    def _intermediate_table(self) -> str: ...
    @cached_property
    def _intermediate_name(self) -> str: ...
    @staticmethod
    def _make_update_from(element_name: str, key_name: str, field_names: NAMES, from_name: str, from_key_name: str, from_field_names: NAMES) -> str: ...
    def _get_field_names(self) -> NAMES: ...
    @property
    def target(self) -> FeatureClass: ...
    @property
    def select(self) -> str: ...
    @property
    def insert(self) -> str: ...
    @property
    def update(self) -> str: ...


class AbstractSpatialQuery(AbstractSourceQuery, metaclass=ABCMeta):

    _element: FeatureClass
    _operator: FeatureClass

    def __init__(self, source: FeatureClass, target: FeatureClass | None,
                 operator: FeatureClass, *, xy_tolerance: XY_TOL) -> None: ...
    @property
    def _has_zm(self) -> HasZM: ...
    def _shared_extent(self, element: FeatureClass) -> EXTENT: ...
    def _get_extent_where(self, element: FeatureClass) -> str: ...
    @cached_property
    def has_intersection(self) -> bool: ...
    @cached_property
    def zm_config(self) -> ZMConfig: ...
    @property
    def select_operator(self) -> str: ...
    @property
    def select_disjoint(self) -> str: ...
    @property
    def operator(self) -> FeatureClass: ...
    @cached_property
    def operator_crs(self) -> CRS: ...
    @cached_property
    def operator_extent(self) -> EXTENT: ...
    @cached_property
    def operator_transformer(self) -> Callable | None: ...


class AbstractSpatialAttribute(AbstractSpatialQuery, metaclass=ABCMeta):

    _attr_option: AttributeOption

    def __init__(self, source: FeatureClass, target: FeatureClass | None,
                 operator: FeatureClass, attribute_option: AttributeOption, *,
                 xy_tolerance: XY_TOL) -> None: ...
    @cache
    def _field_names_and_count(self, element: FeatureClass) -> tuple[int, str, str]: ...
    def _get_fields(self, element: ELEMENT) -> FIELDS: ...
    def _get_unique_fields(self) -> FIELDS: ...
    @staticmethod
    def _make_fid_field(field, element: ELEMENT): ...
    def _avoid_name_clash(self, field): ...
    def _build_insert(self, element: FeatureClass, fields: FIELDS) -> str: ...
    @property
    def input_fid_source(self): ...
    @property
    def input_fid_operator(self): ...
    @cached_property
    def output_fid_source(self): ...
    @cached_property
    def output_fid_operator(self): ...
    @property
    def insert(self) -> str: ...


class BaseQuerySelect(AbstractSourceQuery):

    _where_clause: str

    def __init__(self, source: FeatureClass, target: FeatureClass | Table,
                 where_clause: str = ..., xy_tolerance: XY_TOL = ...) -> None: ...
    @property
    def select(self) -> str: ...
    @property
    def insert(self) -> str: ...


class AbstractQueryGroup(GroupQueryMixin, AbstractSourceQuery,
                         metaclass=ABCMeta):
    _fields: FIELDS
    _group_names: str

    def __init__(self, source: 'FeatureClass', target: 'FeatureClass', *,
                 fields: FIELDS, xy_tolerance: XY_TOL) -> None: ...
    @property
    def insert(self) -> str: ...
    @cached_property
    def group_count(self) -> int: ...
    @property
    def select_geometry(self) -> str: ...


class AbstractQueryDissolve(AbstractQueryGroup):

    _as_multi_part: bool

    def __init__(self, source: FeatureClass, target: FeatureClass, *,
                 fields: FIELDS, as_multi_part: bool,
                 xy_tolerance: XY_TOL) -> None: ...
    def dissolved_geometries(self) -> Generator[dict[int, BaseMultipartGeometry], None, None]: ...
