# -*- coding: utf-8 -*-
"""
Type stubs for query.analysis.proximity module
"""


from abc import ABCMeta
from concurrent.futures.thread import ThreadPoolExecutor as PoolExecutor
from functools import cache, cached_property
from sqlite3 import Connection
from typing import Callable, Generator, Iterator, NamedTuple, Type

from fudgeo import FeatureClass, Field, MemoryGeoPackage
from numpy import ndarray
from shapely import MultiPolygon

from spyops.crs.enumeration import DistanceUnit
from spyops.crs.unit import DecimalDegrees, LinearUnit
from spyops.query.base import AbstractQueryDissolve
from spyops.shared.enumeration import BufferTypeOption, EndOption, SideOption
from spyops.shared.hint import FIELDS, XY_TOL



class BufferConfig(NamedTuple):
    distance: Field | LinearUnit | DecimalDegrees
    buffer_type: BufferTypeOption
    side_option: SideOption
    end_option: EndOption
    resolution: int


class AbstractQueryBufferDissolve(AbstractQueryDissolve, metaclass=ABCMeta):
    def __init__(self, source: FeatureClass, target: FeatureClass, *,
                 distance: Field | LinearUnit | DecimalDegrees,
                 buffer_type: BufferTypeOption, fields: FIELDS | None,
                 side_option: SideOption, end_option: EndOption,
                 resolution: int, xy_tolerance: XY_TOL, ) -> None: ...

    _counter: int
    _config: BufferConfig

    @property
    def _is_distance_from_field(self) -> bool: ...
    @cached_property
    def _is_numeric_field(self) -> bool: ...
    @cached_property
    def _unit_types(self) -> tuple[bool, bool]: ...
    @cached_property
    def buffer_type(self) -> BufferTypeOption: ...
    @cached_property
    def _buffer_function(self) -> Callable: ...
    def _build_distance_field(self) -> str: ...
    def _get_target_shape_type(self) -> str: ...
    @cached_property
    def source_transformer(self) -> Callable | None: ...
    @staticmethod
    def _fetch_features(connection: Connection, sql: str, size: int, step: int,) -> tuple[list[tuple], ndarray]: ...
    def _convert_unit(self, geometries: ndarray, unit: LinearUnit | DecimalDegrees,) -> ndarray: ...
    def _convert_units(self, geometries: ndarray, units: list[LinearUnit | DecimalDegrees | None],) -> ndarray: ...
    @cache
    def _get_conversion_factor(self) -> float: ...
    def show_warning(self) -> None: ...
    def dissolved_geometries(self) -> Generator[dict[int, MultiPolygon], None, None]: ...
    def _from_field(self, sql: str, size: int, steps: int, ) -> Generator[dict[int, MultiPolygon], None, None]: ...
    def _from_distance(self, sql: str, size: int, steps: int, ) -> Generator[dict[int, MultiPolygon], None, None]: ...
    def _dissolve_and_transform(self, geometries: ndarray, ids: ndarray, ) -> dict[int, MultiPolygon]: ...
    def _dissolve_polygons(self, geometries: ndarray, ids: ndarray,) -> tuple[list, ndarray]: ...
    def _get_units(self, features: list[tuple],) -> tuple[list[LinearUnit | DecimalDegrees | None], ndarray]: ...
    def _get_distances(self, geometries: ndarray, units: list[LinearUnit | DecimalDegrees | None],) -> tuple[ndarray, ndarray]: ...
    def _get_distances_broadcast(self, geometries: ndarray, unit: LinearUnit | DecimalDegrees,) -> tuple[ndarray, ndarray]: ...
    @property
    def source(self) -> FeatureClass: ...


class QueryBufferDissolveList(AbstractQueryBufferDissolve):
    def _get_unique_fields(self) -> FIELDS: ...
    @property
    def select(self) -> str: ...
    @property
    def select_geometry(self) -> str: ...
    def _from_field(self, sql: str, size: int, steps: int,) -> Generator[dict[int, MultiPolygon], None, None]: ...
    def _from_distance(self, sql: str, size: int, steps: int,) -> Generator[dict[int, MultiPolygon], None, None]: ...


class QueryBufferDissolveAll(AbstractQueryBufferDissolve):
    def _get_unique_fields(self) -> FIELDS: ...
    @property
    def select(self) -> str: ...
    @property
    def select_geometry(self) -> str: ...
    @cached_property
    def group_count(self) -> int: ...
    def _from_field(self, sql: str, size: int, steps: int,) -> Generator[dict[int, MultiPolygon], None, None]: ...
    def _from_distance(self, sql: str, size: int, steps: int,) -> Generator[dict[int, MultiPolygon], None, None]: ...
    def _build_single_polygon(self, dissolved: dict[int, MultiPolygon],) -> Generator[dict[int, MultiPolygon], None, None]: ...


class QueryBufferDissolveNone(AbstractQueryBufferDissolve):
    def _get_unique_fields(self) -> FIELDS: ...
    @property
    def select(self) -> str: ...
    @property
    def select_geometry(self) -> str: ...
    @cached_property
    def group_count(self) -> int: ...
    def _from_field(self, sql: str, size: int, steps: int,) -> Generator[dict[int, MultiPolygon], None, None]: ...
    def _from_distance(self, sql: str, size: int, steps: int,) -> Generator[dict[int, MultiPolygon], None, None]: ...
    def _dissolve_polygons(self, geometries: ndarray, ids: ndarray,) -> tuple[ndarray, ndarray]: ...


class QueryMultipleBuffer(AbstractQueryBufferDissolve):
    def __init__(self, source: FeatureClass, target: FeatureClass,
                 distance_unit: DistanceUnit, distances: list[float], *,
                 buffer_type: BufferTypeOption = BufferTypeOption.PLANAR,
                 overlapping: bool = False, only_outside: bool = False,
                 field_name: str | None = None, resolution: int = 32,
                 xy_tolerance: XY_TOL = None, ) -> None: ...

    _distance_unit: DistanceUnit
    _distances: list[float]
    _overlapping: bool
    _only_outside: bool
    _field_name: str | None

    def __iter__(self) -> Iterator[tuple[QueryBufferDissolveNone, str]]: ...
    def _make_update_sql(self, distance: LinearUnit | DecimalDegrees) -> str: ...
    def _distances_and_labels(self,) -> tuple[list[LinearUnit | DecimalDegrees], list[str]]: ...
    def _distances_labels_overlap(self, unit: Type[LinearUnit | DecimalDegrees],) -> tuple[list[LinearUnit | DecimalDegrees], list[str]]: ...
    def _distance_labels_sans(self, unit: Type[LinearUnit | DecimalDegrees],) -> tuple[list[LinearUnit | DecimalDegrees], list[str]]: ...
    @staticmethod
    def _make_labels(units: list[LinearUnit | DecimalDegrees]) -> list[str]: ...
    def _include_original_polygon(self, unit: Type[LinearUnit | DecimalDegrees],) -> list[LinearUnit | DecimalDegrees]: ...
    @cached_property
    def _distance_field(self) -> Field | None: ...
    def dissolved_geometries(self) -> list[tuple[MultiPolygon, tuple]]: ...
    def _create_dissolved_source(self, memory: MemoryGeoPackage) -> FeatureClass: ...
    def _resolve_overlaps(self, ordered: list[tuple[MultiPolygon, tuple]], distances: list[float],) -> list[tuple[MultiPolygon, tuple]]: ...
    def _build_only_outside(self, geoms: list[MultiPolygon], distances: list[float],) -> list[MultiPolygon]: ...
    def _build_no_overlaps(self, geoms: list[MultiPolygon]) -> list[MultiPolygon]: ...
    @property
    def select(self) -> str: ...
    @property
    def select_geometry(self) -> str: ...
    @property
    def insert(self) -> str: ...
    def _from_field(self, sql: str, size: int, steps: int,) -> Generator[dict[int, MultiPolygon], None, None]: ...
    def _from_distance(self, sql: str, size: int, steps: int,) -> Generator[dict[int, MultiPolygon], None, None]: ...
    @staticmethod
    def _get_side_option(source: FeatureClass, only_outside: bool) -> SideOption: ...
    def _get_unique_fields(self) -> FIELDS: ...
