# -*- coding: utf-8 -*-
"""
Type stubs for query.management.features module
"""


from abc import ABCMeta
from functools import cached_property
from operator import itemgetter
from sqlite3 import Connection
from typing import Callable, Generator, Union

from fudgeo import FeatureClass, Field, SpatialReferenceSystem, Table
from numpy import ndarray
from pyproj import CRS
from shapely import Polygon

from spyops.crs.enumeration import AreaUnit, LengthUnit
from spyops.environment.core import HasZM, ZMConfig
from spyops.query.base import (
    AbstractQueryGroup, AbstractSourceQuery, AbstractSourceUpdateQuery,
    BaseQuerySelect)
from spyops.shared.enumeration import (
    GeometryAttribute, MinimumGeometryOption, PointTypeOption, WeightOption)
from spyops.shared.hint import (
    ELEMENT, FIELDS, GRID_SIZE, LINE_TYPE, NAMES, POINT_TYPE, XY_TOL)



class QueryMultiPartToSinglePart(AbstractSourceQuery):
    def __init__(self, source: FeatureClass, target: FeatureClass) -> None: ...
    def _get_target_shape_type(self) -> str: ...
    def _get_unique_fields(self) -> FIELDS: ...
    @property
    def select(self) -> str: ...
    @property
    def insert(self) -> str: ...
    @cached_property
    def source_transformer(self) -> Callable | None: ...
    @property
    def source(self) -> FeatureClass: ...


class QueryCopyFeatures(BaseQuerySelect):
    pass


class QueryCheckGeometry(BaseQuerySelect):
    def __init__(self, source: FeatureClass, target: Table, xy_tolerance: XY_TOL) -> None: ...
    @property
    def _fields(self) -> FIELDS: ...
    @cached_property
    def grid_size(self) -> GRID_SIZE: ...
    @property
    def target(self) -> Table: ...
    @cached_property
    def target_empty(self) -> Table: ...
    @property
    def source(self) -> FeatureClass: ...


class QueryRepairGeometry(AbstractSourceUpdateQuery):
    @property
    def _short_name(self) -> str: ...
    def _prepare_source(self) -> None: ...
    @property
    def _intermediate_fields(self) -> FIELDS: ...
    def _get_field_names(self) -> NAMES: ...
    @property
    def drop_empty(self) -> str: ...
    @property
    def truncate(self) -> str: ...
    @property
    def insert_identifiers(self) -> str: ...
    @property
    def update(self) -> str: ...
    @property
    def source(self) -> FeatureClass: ...


class QueryAddXYCoordinates(AbstractSourceUpdateQuery):

    _option: WeightOption

    def __init__(self, source: FeatureClass, weight_option: WeightOption) -> None: ...
    def _get_field_names(self) -> NAMES: ...
    @property
    def _short_name(self) -> str: ...
    def _prepare_source(self) -> None: ...
    @property
    def _intermediate_fields(self) -> FIELDS: ...
    @property
    def centroid_getter(self) -> Callable: ...
    @property
    def source(self) -> FeatureClass: ...


class QueryCalculateGeometryAttributes(AbstractSourceUpdateQuery):

    _field: Field
    _attribute: GeometryAttribute
    _option: WeightOption
    _length_unit: LengthUnit
    _area_unit: AreaUnit

    def __init__(self, source: FeatureClass, field: Field,
                 geometry_attribute: GeometryAttribute, *,
                 weight_option: WeightOption, length_unit: LengthUnit,
                 area_unit: AreaUnit, ) -> None: ...
    def _get_field_names(self) -> NAMES: ...
    @property
    def _point_attributes(self) -> tuple[GeometryAttribute, ...]: ...
    @property
    def _centroid_attributes(self) -> tuple[GeometryAttribute, ...]: ...
    @property
    def _extent_minimum_attributes(self) -> tuple[GeometryAttribute, ...]: ...
    @property
    def _extent_maximum_attributes(self) -> tuple[GeometryAttribute, ...]: ...
    @property
    def _line_start_attributes(self) -> tuple[GeometryAttribute, ...]: ...
    @property
    def _line_end_attributes(self) -> tuple[GeometryAttribute, ...]: ...
    @property
    def _inside_attributes(self) -> tuple[GeometryAttribute, ...]: ...
    @property
    def _output_crs(self) -> CRS: ...
    def _length_getter(self) -> Callable: ...
    def _area_getter(self) -> Callable: ...
    @property
    def _short_name(self) -> str: ...
    def _prepare_source(self) -> None: ...
    @property
    def _intermediate_fields(self) -> FIELDS: ...
    @property
    def item_getter(self) -> Callable: ...
    @property
    def attribute_getter(self) -> Callable: ...
    @property
    def source(self) -> FeatureClass: ...


class QueryXYTablePoint(AbstractSourceQuery):

    _fields: tuple[Field | None, ...]
    _coord_sys: CRS | SpatialReferenceSystem

    def __init__(self, source: ELEMENT, target: FeatureClass,
                 fields: tuple[Field | None, ...],
                 coordinate_system: CRS | SpatialReferenceSystem, ) -> None: ...
    def _get_target_shape_type(self) -> str: ...
    @property
    def point_class(self) -> POINT_TYPE: ...
    @property
    def item_getter(self) -> itemgetter: ...
    @property
    def select(self) -> str: ...
    @property
    def insert(self) -> str: ...
    @cached_property
    def source_transformer(self) -> Callable | None: ...
    @property
    def filter_extent(self) -> Polygon | None: ...
    @property
    def _has_zm(self) -> HasZM: ...
    @property
    def zm_config(self) -> ZMConfig: ...
    @cached_property
    def spatial_reference_system(self) -> SpatialReferenceSystem: ...


class QueryXYTableLine(QueryXYTablePoint):
    def __init__(self, source: ELEMENT, target: FeatureClass,
                 fields: tuple[Field, Field, Field, Field],
                 coordinate_system: CRS | SpatialReferenceSystem, ) -> None: ...
    def _get_target_shape_type(self) -> str: ...
    @cached_property
    def source_transformer(self) -> Callable | None: ...
    @property
    def filter_extent(self) -> Polygon | None: ...
    @property
    def _has_zm(self) -> HasZM: ...
    @cached_property
    def spatial_reference_system(self) -> SpatialReferenceSystem: ...


class QueryFeatureEnvelopeToPolygon(BaseQuerySelect):

    _as_multi_part: bool

    def __init__(self, source: FeatureClass, target: FeatureClass, as_multi_part: bool) -> None: ...
    def _get_unique_fields(self) -> FIELDS: ...
    def _get_target_shape_type(self) -> str: ...
    @property
    def as_multi_part(self) -> bool: ...
    @property
    def extent_getter(self) -> Callable: ...
    @property
    def select(self) -> str: ...
    @cached_property
    def zm_config(self) -> ZMConfig: ...
    @property
    def source(self) -> FeatureClass: ...


class AbstractQueryMinimumBoundingGeometry(AbstractQueryGroup, metaclass=ABCMeta):

    _geometry_type: MinimumGeometryOption
    _add_attrs: bool

    def __init__(self, source: 'FeatureClass', target: 'FeatureClass',
                 geometry_type: MinimumGeometryOption, *,
                 add_geometric_attributes: bool, fields: FIELDS) -> None: ...
    @property
    def add_attributes(self) -> bool: ...
    @cached_property
    def _bounding_function(self) -> Callable: ...
    @cached_property
    def _attribute_function(self) -> Callable: ...
    def _get_target_shape_type(self) -> str: ...
    @cached_property
    def source_transformer(self) -> Callable | None: ...
    def grouped_geometries(self) -> Generator[dict[int, tuple], None, None]: ...
    def _process_geometries(self, ids: 'ndarray', geometries: Union['ndarray', list]) -> dict[int, tuple]: ...
    def _get_key_fields(self) -> tuple[Field, ...]: ...


class QueryMinimumBoundingGeometryList(AbstractQueryMinimumBoundingGeometry):
    def _get_unique_fields(self) -> FIELDS: ...
    def _get_key_fields(self) -> tuple[Field, ...]: ...
    @property
    def select(self) -> str: ...
    @property
    def select_geometry(self) -> str: ...
    def grouped_geometries(self) -> Generator[dict[int, tuple], None, None]: ...
    def _fetch_features(self, connection: 'Connection', sql: str, size: int, step: int) -> tuple[list[tuple], 'ndarray']: ...


class QueryMinimumBoundingGeometryAll(AbstractQueryMinimumBoundingGeometry):
    def _get_unique_fields(self) -> FIELDS: ...
    def _get_key_fields(self) -> tuple[Field, ...]: ...
    @property
    def select(self) -> str: ...
    @property
    def select_geometry(self) -> str: ...
    @cached_property
    def group_count(self) -> int: ...
    def grouped_geometries(self) -> Generator[dict[int, tuple], None, None]: ...


class QueryMinimumBoundingGeometryNone(AbstractQueryMinimumBoundingGeometry):
    def _get_unique_fields(self) -> FIELDS: ...
    def _get_key_fields(self) -> tuple[Field, ...]: ...
    @property
    def select(self) -> str: ...
    @property
    def select_geometry(self) -> str: ...
    @cached_property
    def group_count(self) -> int: ...
    def grouped_geometries(self) -> Generator[dict[int, tuple], None, None]: ...


class QueryFeatureToPoint(BaseQuerySelect):

    _inside: bool
    _option: WeightOption

    def __init__(self, source: 'FeatureClass', target: 'FeatureClass',
                 inside: bool, weight_option: WeightOption) -> None: ...
    def _get_unique_fields(self) -> FIELDS: ...
    def _get_target_shape_type(self) -> str: ...
    @property
    def coordinate_getter(self) -> Callable: ...
    @property
    def point_class(self) -> POINT_TYPE: ...
    @property
    def select(self) -> str: ...
    @cached_property
    def zm_config(self) -> 'ZMConfig': ...


class QueryFeatureVerticesToPoints(BaseQuerySelect):

    _point_type: PointTypeOption

    def __init__(self, source: 'FeatureClass', target: 'FeatureClass',
                 point_type: PointTypeOption) -> None: ...
    def _get_unique_fields(self) -> FIELDS: ...
    def _get_target_shape_type(self) -> str: ...
    @property
    def vertex_getter(self) -> Callable: ...
    @property
    def select(self) -> str: ...
    @cached_property
    def source_transformer(self) -> Callable | None: ...


class QuerySplitLineAtVertices(BaseQuerySelect):
    def _get_unique_fields(self) -> FIELDS: ...
    def _get_target_shape_type(self) -> str: ...
    @property
    def select(self) -> str: ...
    @property
    def segment_getter(self) -> Callable: ...
    @cached_property
    def source_transformer(self) -> Callable | None: ...


class QueryPolygonToLine(BaseQuerySelect):
    def _get_unique_fields(self) -> FIELDS: ...
    def _get_target_shape_type(self) -> str: ...
    @property
    def select(self) -> str: ...
    @property
    def polygon_getter(self) -> Callable: ...
    @property
    def line_class(self) -> LINE_TYPE: ...
    @cached_property
    def source_transformer(self) -> Callable | None: ...
