# -*- coding: utf-8 -*-
"""
Type stubs for query.management.features module
"""

from functools import cached_property
from operator import itemgetter
from typing import Callable, Type

from fudgeo import FeatureClass, Field, SpatialReferenceSystem, Table
from fudgeo.geometry import Point, PointM, PointZ, PointZM
from pyproj import CRS
from shapely import Polygon

from spyops.crs.enumeration import AreaUnit, LengthUnit
from spyops.environment.core import HasZM, ZMConfig
from spyops.query.base import AbstractSourceQuery, AbstractSourceUpdateQuery, BaseQuerySelect
from spyops.shared.enumeration import GeometryAttribute, WeightOption
from spyops.shared.hint import ELEMENT, FIELDS, GRID_SIZE, NAMES, XY_TOL



class QueryMultiPartToSinglePart(AbstractSourceQuery):
    def __init__(self, source: FeatureClass, target: FeatureClass) -> None: ...
    def _get_target_shape_type(self) -> str: ...
    def _get_unique_fields(self) -> FIELDS: ...
    @property
    def select(self) -> str: ...
    @property
    def insert(self) -> str: ...
    @cached_property
    def source_transformer(self) -> Callable | None: ...


class QueryCopyFeatures(BaseQuerySelect):
    pass


class QueryCheckGeometry(BaseQuerySelect):
    def __init__(self, source: FeatureClass, target: Table, xy_tolerance: XY_TOL) -> None: ...
    @property
    def _fields(self) -> FIELDS: ...
    @cached_property
    def grid_size(self) -> GRID_SIZE: ...
    @property
    def target(self) -> Table: ...
    @cached_property
    def target_empty(self) -> Table: ...
    @property
    def source(self) -> FeatureClass: ...


class QueryRepairGeometry(AbstractSourceUpdateQuery):
    @property
    def _short_name(self) -> str: ...
    def _prepare_source(self) -> None: ...
    @property
    def _intermediate_fields(self) -> FIELDS: ...
    def _get_field_names(self) -> NAMES: ...
    @property
    def drop_empty(self) -> str: ...
    @property
    def truncate(self) -> str: ...
    @property
    def insert_identifiers(self) -> str: ...
    @property
    def update(self) -> str: ...
    @property
    def source(self) -> FeatureClass: ...


class QueryAddXYCoordinates(AbstractSourceUpdateQuery):
    def __init__(self, source: FeatureClass, weight_option: WeightOption) -> None: ...
    def _get_field_names(self) -> NAMES: ...
    @property
    def _short_name(self) -> str: ...
    def _prepare_source(self) -> None: ...
    @property
    def _intermediate_fields(self) -> FIELDS: ...
    @property
    def centroid_getter(self) -> Callable: ...


class QueryCalculateGeometryAttributes(AbstractSourceUpdateQuery):
    def __init__(
        self,
        source: FeatureClass,
        field: Field,
        geometry_attribute: GeometryAttribute,
        *,
        weight_option: WeightOption,
        length_unit: LengthUnit,
        area_unit: AreaUnit,
    ) -> None: ...
    def _get_field_names(self) -> NAMES: ...
    @property
    def _point_attributes(self) -> tuple[GeometryAttribute, ...]: ...
    @property
    def _centroid_attributes(self) -> tuple[GeometryAttribute, ...]: ...
    @property
    def _extent_minimum_attributes(self) -> tuple[GeometryAttribute, ...]: ...
    @property
    def _extent_maximum_attributes(self) -> tuple[GeometryAttribute, ...]: ...
    @property
    def _line_start_attributes(self) -> tuple[GeometryAttribute, ...]: ...
    @property
    def _line_end_attributes(self) -> tuple[GeometryAttribute, ...]: ...
    @property
    def _inside_attributes(self) -> tuple[GeometryAttribute, ...]: ...
    @property
    def _output_crs(self) -> CRS: ...
    def _length_getter(self) -> Callable: ...
    def _area_getter(self) -> Callable: ...
    @property
    def _short_name(self) -> str: ...
    def _prepare_source(self) -> None: ...
    @property
    def _intermediate_fields(self) -> FIELDS: ...
    @property
    def item_getter(self) -> Callable: ...
    @property
    def attribute_getter(self) -> Callable: ...


class QueryXYTablePoint(AbstractSourceQuery):
    def __init__(
        self,
        source: ELEMENT,
        target: FeatureClass,
        fields: tuple[Field | None, ...],
        coordinate_system: CRS | SpatialReferenceSystem,
    ) -> None: ...
    def _get_target_shape_type(self) -> str: ...
    @property
    def point_class(self) -> Type[Point | PointZ | PointM | PointZM]: ...
    @property
    def item_getter(self) -> itemgetter: ...
    @property
    def select(self) -> str: ...
    @property
    def insert(self) -> str: ...
    @cached_property
    def source_transformer(self) -> Callable | None: ...
    @property
    def filter_extent(self) -> Polygon | None: ...
    @property
    def _has_zm(self) -> HasZM: ...
    @property
    def zm_config(self) -> ZMConfig: ...
    @cached_property
    def spatial_reference_system(self) -> SpatialReferenceSystem: ...


class QueryXYTableLine(QueryXYTablePoint):
    def __init__(
        self,
        source: ELEMENT,
        target: FeatureClass,
        fields: tuple[Field, Field, Field, Field],
        coordinate_system: CRS | SpatialReferenceSystem,
    ) -> None: ...
    def _get_target_shape_type(self) -> str: ...
    @cached_property
    def source_transformer(self) -> Callable | None: ...
    @property
    def filter_extent(self) -> Polygon | None: ...
    @property
    def _has_zm(self) -> HasZM: ...
    @cached_property
    def spatial_reference_system(self) -> SpatialReferenceSystem: ...


class QueryFeatureEnvelopeToPolygon(BaseQuerySelect):
    def __init__(self, source: FeatureClass, target: FeatureClass, as_multi_part: bool) -> None: ...
    def _get_unique_fields(self) -> FIELDS: ...
    def _get_target_shape_type(self) -> str: ...
    @property
    def as_multi_part(self) -> bool: ...
    @property
    def extent_getter(self) -> Callable: ...
    @property
    def select(self) -> str: ...
    @cached_property
    def zm_config(self) -> ZMConfig: ...
